### ISSUE TITLE
How soon is 'Coming soon' ?

### ISSUE THREAD

**Issue by apeters1971** [extfuse/extfuse#1]
Is it still planned to be published?

**Comment by lantz** [comment]
Still no code for this?

**Comment by justicezyx** [comment]
It's usually surprising that after the paper is already accepted and the link to source code is linked on the preprint, there is still no code.

Given that this is a fairly practical and very valuable, but not much fundamental-changing work. And I assume the reviewers do not have access to the source code either, right? I am not sure how they decide the novelty if there is no code.

**Comment by hankliu5** [comment]
Are these the source code they implemented?

https://github.com/torvalds/linux/compare/master...extfuse:ExtFUSE-1.0
https://github.com/libfuse/libfuse/compare/master...extfuse:ExtFUSE-1.0

**Comment by ashishbijlani** [comment]
Yes, those are the changes you need in the Linux kernel and LibFUSE.

**Comment by ashishbijlani** [comment]
I've added lib extfuse code as well.
