### ISSUE TITLE
Component version mismatch

### ISSUE THREAD

**Issue by caoruidong** [extfuse/extfuse#4]
I tried extfuse, but failed. I think extfuse, kernel and libfuse don't match each other. For example, data struct  fuse_init_out in libfuse isn't same with that in kernel. So program will panic.

**Comment by ashishbijlani** [comment]
This is a lib fuse issue. The definition of fuse_init_out data struct inlibfuse is inconsistent with its in-kernel definition.

libfuse 3.4.1 (2018-12-22) uses the following:

`
    uint32_t    max_write;
    uint32_t    time_gran;
    uint32_t    unused[9];
};
`

Whereas, the kernel uses:

`
    uint32_t    max_write;
    uint32_t    time_gran;
    uint16_t    max_pages;
    uint16_t    padding;
    uint32_t    unused[8];
};
`

This [commit](https://github.com/libfuse/libfuse/commit/4ae58ffd9b149cc3d7aeea72d4d51248a77af39b) seems to fix it in newer versions of libfuse

However, I've fixed this in ExtFUSE-1.0 branch of LibFuse [here](https://github.com/extfuse/libfuse)
